config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  resources :restaurants
  root 'restaurants#index'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants, dependent: :destroy
  validates_presence_of :username

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :owner
  validates_presence_of :name, :description, :owner_id
  validates_uniqueness_of :name
  # validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "invalid phone number" }
  # validates :weburl, format: {with: URI::regexp(%w(http https)), message: 'invalide web address'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_owner!, except: [ :index, :show ]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = current_owner.restaurants.build
  end

  def edit
    @restaurant = current_owner.restaurants.find(params[:id])
  end

  def create
    @restaurant = current_owner.restaurants.build(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant created"
    else
      render action: "new"
    end
  end

  def update
    @restaurant = current_owner.restaurants.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      redirect_to @restaurant, notice: "Restaurant updated"
    else
      render action: "edit"
    end
  end

  def destroy
    @restaurant = current_owner.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_url, notice: "Restaurant deleted"
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :phone, :weburl)
  end		

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Opentable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_owner %>
    <%= link_to "logout #{current_owner.username}", destroy_owner_session_path, method: :delete %>
 <% else %>
   <%= link_to "login", new_owner_session_path%>
  <% end  %>



<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :weburl %><br>
    <%= f.text_field :weburl %>
  </div><div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editing Restaurant</h1>

<%= render partial: 'form' %>

<!-- <%= link_to 'Show', @restaurant %> |-->
<%= link_to 'Save', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to "Show", restaurant %></td>
        <% if restaurant.owner == current_owner %>
          <td><%= link_to "Edit", edit_restaurant_path(restaurant) %></td>
          <td><%= link_to "Delete", restaurant, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% end %>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to "New Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New Restaurant</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>
<p>
  <strong>Review:</strong>
  <%= @restaurant.description %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @restaurant.phone %>
</p>
<p>
  <strong>Website:</strong>
  <%= @restaurant.weburl %>
</p>

<% if @restaurant.owner == current_owner %>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<% end %>
<%= link_to 'Back', restaurants_path %>